name: Deploy to Vercel
on:
  push:
    branches: [ main, testing ]
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js (required to install Vercel CLI)
        uses: actions/setup-node@v3

      - name: Install Vercel CLI
        run: npm install --global vercel
        
      - name: Deploy static content to Vercel
        run: |
          productionFlag=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            productionFlag="--prod"
          fi
          vercel . --token ${VERCEL_TOKEN} $productionFlag
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
